---
services:
  golangfromzero:
    image: fabianoflorentino/golangfromzero:v1.0
    build:
      context: .
      dockerfile: build/Dockerfile
    env_file:
      - configs/.env
    networks:
      - golangfromzero
    volumes:
      - .:/golangfromzero
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "ps aux |grep 'sleep' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  golangfromzero:
    name: golangfromzero
    driver: bridge
